# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8085
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/auth_server/oauth/token
      userAuthorizationUri: http://localhost:8080/auth_server/oauth/authorize
      clientId: curl_client
      clientSecret: user
      scope: read,write
    resource:
      userInfoUri: http://localhost:8083/product
      prefer-token-info: false
      filter-order: 3



# Proxies the calls to http://localhost:8080/api/* to our REST service at http://localhost:9000/*
# and automatically includes our OAuth2 token in the request headers
zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:8083
    product:
      path: /product/**
      url: http://localhost:8083/product


# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2